### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by coreyker** [hoffoo/moov-csv#1]
Here is the traceback I get when running:

$ python3 moovplot.py --csv /tmp/bk
Traceback (most recent call last):
  File "moovplot.py", line 90, in <module>
    dbfile = readfile(bkfile)
  File "moovplot.py", line 31, in readfile
    tar = tarfile.open(0, "r", buf)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tarfile.py", line 1568, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gzip.py", line 169, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not int

I tried modifying the print statements and using Python2. That runs without error, but the output data is wrong.

Any thoughts would be much appreciated

**Comment by coreyker** [comment]
To follow up, on line 31 I replaced the 0 with None and then the program runs without error. However, the output isn't quite right. Here's my output:

swims:
duration,lap_count,stroke_count,distance,distance_per_stroke,stroke_rate
1781,57,567,1425,


runs:
duration,average_cadence,average_speed,distance

I haven't done any runs, so that part is fine. The duration, lap count, stroke count and distance look right, but the rest of the data is missing...

**Comment by hoffoo** [comment]
hi @coreyker , can you paste me a full diff of what you changed to get that output?

The stacktrace is for python 3, with python 2 and no modification you still get bad data?

**Comment by coreyker** [comment]
Sure here's the diff:
```
diff --git a/moovplot.py b/moovplot.py
index 5ad19b9..a4d3736 100755
--- a/moovplot.py
+++ b/moovplot.py
@@ -28,7 +28,7 @@ def readfile(path):

     #unzip
     buf = io.BytesIO(zlib.decompress(f.read()))
-    tar = tarfile.open(0, "r", buf)
+    tar = tarfile.open(None, "r", buf)

     # extract sqlite databases from archive
     dbtar = None
@@ -67,11 +67,13 @@ def query(sql, q, fields):
                     js = json.loads(col)
                     if f in js:
                         print("%s," % js[f], end="")
+                        # print "%s," % js[f],
                     continue

                 # failed to get this col from json, try from the row
                 try:
                     print("%s," % r[f], end="")
+                    # print "%s," % r[f],
```
To get it to run with Python2 I have to used the commented print statements as the current ones are for Python3 only, I believe. When I run with Python2 it outputs this:

swims:
duration,lap_count,stroke_count,distance,distance_per_stroke,stroke_rate
1781, 1781, 1781, ()


runs:
duration,average_cadence,average_speed,distance

So it looks like the duration just gets repeated a bunch of times.

I was hoping to pull out all of the data shown in the app (per stroke speed, stroke count, etc).

Does that help?

**Comment by hoffoo** [comment]
Can you try it with python 2 and no modifications? Unfortunately I don't have a way to reproduce it anymore (i dont have the device).

**Comment by coreyker** [comment]
I tried with Python 2 and no modifications. It chokes on the print statements unless I add
```
from __future__ import print_function
```
to the top of the file. That fixes the traceback error, but the output is still wrong.

Thanks for your help. I'm not sure I have the skills to fix this, but if I do I will report back.

**Comment by hoffoo** [comment]
Can you paste the python 2 traceback?

**Comment by coreyker** [comment]
Python 2 traceback:

```
$ ./moovplot.py
  File "./moovplot.py", line 70
    print("%s," % js[f], end="")
                            ^
SyntaxError: invalid syntax
```
